using Se7en.OpenCl.Native;

namespace Se7en.OpenCl
{  
    public enum ErrorCode  : int // cl_int
    {
        Unknown = NativeCl.CL_TRUE,
		Success = NativeCl.CL_BUILD_SUCCESS,
		DeviceNotFound = NativeCl.CL_DEVICE_NOT_FOUND,
		DeviceNotAvailable = NativeCl.CL_DEVICE_NOT_AVAILABLE,
		CompilerNotAvailable = NativeCl.CL_COMPILER_NOT_AVAILABLE,
		MemObjectAllocationFailure = NativeCl.CL_MEM_OBJECT_ALLOCATION_FAILURE,
		OutOfResources = NativeCl.CL_OUT_OF_RESOURCES,
		OutOfHostMemory = NativeCl.CL_OUT_OF_HOST_MEMORY,
		ProfilingInfoNotAvailable = NativeCl.CL_PROFILING_INFO_NOT_AVAILABLE,
		MemCopyOverlap = NativeCl.CL_MEM_COPY_OVERLAP,
		ImageFormatMismatch = NativeCl.CL_IMAGE_FORMAT_MISMATCH,
		ImageFormatNotSupported = NativeCl.CL_IMAGE_FORMAT_NOT_SUPPORTED,
		BuildProgramFailure = NativeCl.CL_BUILD_PROGRAM_FAILURE,
		MapFailure = NativeCl.CL_MAP_FAILURE,
		InvalidValue = NativeCl.CL_INVALID_VALUE,
		InvalidDeviceType = NativeCl.CL_INVALID_DEVICE_TYPE,
		InvalidPlatform = NativeCl.CL_INVALID_PLATFORM,
		InvalidDevice = NativeCl.CL_INVALID_DEVICE,
		InvalidContext = NativeCl.CL_INVALID_CONTEXT,
		InvalidQueueProperties = NativeCl.CL_INVALID_QUEUE_PROPERTIES,
		InvalidCommandQueue = NativeCl.CL_INVALID_COMMAND_QUEUE,
		InvalidHostPtr = NativeCl.CL_INVALID_HOST_PTR,
		InvalidMemObject = NativeCl.CL_INVALID_MEM_OBJECT,
		InvalidImageFormatDescriptor = NativeCl.CL_INVALID_IMAGE_FORMAT_DESCRIPTOR,
		InvalidImageSize = NativeCl.CL_INVALID_IMAGE_SIZE,
		InvalidSampler = NativeCl.CL_INVALID_SAMPLER,
		InvalidBinary = NativeCl.CL_INVALID_BINARY,
		InvalidBuildOptions = NativeCl.CL_INVALID_BUILD_OPTIONS,
		InvalidProgram = NativeCl.CL_INVALID_PROGRAM,
		InvalidProgramExecutable = NativeCl.CL_INVALID_PROGRAM_EXECUTABLE,
		InvalidKernelName = NativeCl.CL_INVALID_KERNEL_NAME,
		InvalidKernelDefinition = NativeCl.CL_INVALID_KERNEL_DEFINITION,
		InvalidKernel = NativeCl.CL_INVALID_KERNEL,
		InvalidArgIndex = NativeCl.CL_INVALID_ARG_INDEX,
		InvalidArgValue = NativeCl.CL_INVALID_ARG_VALUE,
		InvalidArgSize = NativeCl.CL_INVALID_ARG_SIZE,
		InvalidKernelArgs = NativeCl.CL_INVALID_KERNEL_ARGS,
		InvalidWorkDimension = NativeCl.CL_INVALID_WORK_DIMENSION,
		InvalidWorkGroupSize = NativeCl.CL_INVALID_WORK_GROUP_SIZE,
		InvalidWorkItemSize = NativeCl.CL_INVALID_WORK_ITEM_SIZE,
		InvalidGlobalOffset = NativeCl.CL_INVALID_GLOBAL_OFFSET,
		InvalidEventWaitList = NativeCl.CL_INVALID_EVENT_WAIT_LIST,
		InvalidEvent = NativeCl.CL_INVALID_EVENT,
		InvalidOperation = NativeCl.CL_INVALID_OPERATION,
		InvalidGlObject = NativeCl.CL_INVALID_GL_OBJECT,
		InvalidBufferSize = NativeCl.CL_INVALID_BUFFER_SIZE,
		InvalidMipLevel = NativeCl.CL_INVALID_MIP_LEVEL,
		
    };
}